config/routes.rb
Rails.application.routes.draw do
  root "main#index"
  scope :admin do
    resources :countries do
      resources :regions
      resources :tour_bases
    end
    resources :regions do
      resources :cities
      resources :tour_bases
    end

    resources :cities do
      resources :tour_bases
    end

    resources :tour_bases
  end

  namespace :view do
    resources :tour_bases, only: [:index]
    resources :countries,only: [] do
      resources :tour_bases, only: [:index]
      resources :regions,only: [] do
        resources :tour_bases, only: [:index]
        resources :cities,only: [] do
          resources :tour_bases, only: [:index]
        end
      end
    end
  end





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2 }
  belongs_to :region
  has_many :tour_base, dependent: :nullify
  accepts_nested_attributes_for :tour_base
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :regions, dependent: :destroy
  has_many :tour_base, through: :regions
  validates :name, presence: true, length: { minimum: 2 }
  accepts_nested_attributes_for :regions
  attr_accessor :delete_confirm
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :cities, dependent: :destroy
  has_many :tour_base, dependent: :destroy
  validates :name, presence: true, length: { minimum: 2 }
  belongs_to :country
  accepts_nested_attributes_for :cities, :tour_base
  attr_accessor :delete_confirm
end

app/models/tour_base.rb
class TourBase < ApplicationRecord
  belongs_to :city, optional: true
  belongs_to :region
  validates :name, presence: true, length: { minimum: 2 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout "application"
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = if params[:region_id].nil?
                City.all
              else
                @region = Region.find(params[:region_id])
                @region.cities
              end
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)
    if @city.save
      redirect_to action: :index
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @city = City.find(params[:id])
  end

  def update
    @city = City.find(params[:id])
    if @city.update(city_params)
      redirect_to action: :index
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @city = City.find(params[:id])
    @city.destroy
    redirect_back fallback_location: cities_path
  end

  private

  def city_params
    params.require(:city).permit(:name, :region_id)
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def index
    @countries = Country.all
    @countries.each do |country|
      next if country.regions.length.zero?

      regions_list = country.regions.reduce('') { |list, r| "#{list}#{r.name}, " }
      regions_list.chomp!(', ')
      country.delete_confirm = "Будут удалены следующие регионы: #{regions_list}"
    end
  end

  def new
    @country = Country.new
  end

  def create
    @country = Country.new(country_params)
    if @country.save
      redirect_to action: :index
    else
      render :new, status: :unprocessable_entity
    end

  end

  def destroy
    @country = Country.find(params[:id])
    @country.destroy
    redirect_to action: :index
  end

  def edit
    @country = Country.find(params[:id])
  end

  def update
    @country = Country.find(params[:id])
    if @country.update(country_params)
      redirect_to action: :index
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  
  def country_params
    params.require(:country).permit(:name)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    redirect_to view_tour_bases_path
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController

  def index
    @regions = if params[:country_id].nil?
                 Region.all
               else
                 @country = Country.find(params[:country_id])
                 @country.regions
               end
    @regions.each do |region|
      next if region.cities.length.zero?

      cities_list = region.cities.reduce('') { |list, c| "#{list}#{c.name}, " }
      cities_list.chomp!(', ')
      region.delete_confirm = "Будут удалены следующие города: #{cities_list}"
    end

  end

  def new
    @region = Region.new
  end

  def create
    @region = Region.new(region_params)
    if @region.save
      redirect_to action: :index
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @region = Region.find(params[:id])
  end

  def update
    @region = Region.find(params[:id])
    if @region.update(region_params)
      redirect_to action: :index
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @region = Region.find(params[:id])
    @region.destroy
    redirect_back fallback_location: regions_path
  end

  private

  def region_params
    params.require(:region).permit(:name, :country_id)
  end
end

app/controllers/tour_bases_controller.rb
class TourBasesController < ApplicationController

  def index
    @tour_bases = if !params[:region_id].nil?
                    @region = Region.find(params[:region_id])
                    @region.tour_base
                  elsif !params[:city_id].nil?
                    @city = City.find(params[:city_id])
                    @city.tour_base
                  elsif !params[:country_id].nil?
                    @country = Country.find(params[:country_id])
                    @country.tour_base
                  else
                    TourBase.all
                  end
  end

  def new
    @tour_base = TourBase.new
  end

  def create
    @tour_base = TourBase.new(tour_base_params)
    if @tour_base.save
      redirect_to action: :index
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @tour_base = TourBase.find(params[:id])
  end

  def update
    @tour_base = TourBase.find(params[:id])
    if @tour_base.update(tour_base_params)
      redirect_to action: :index
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tour_base = TourBase.find(params[:id])
    @tour_base.destroy
    redirect_back fallback_location: tour_bases_path
  end

  private

  def tour_base_params
    params.require(:tour_base).permit(:name, :city_id, :region_id,:description)
  end

end

app/controllers/view/tour_bases_controller.rb
class View::TourBasesController < ApplicationController

  def index
    @tour_bases = TourBase.all
    unless params[:country_id].nil?
      @country = Country.find(params[:country_id])
      @tour_bases = @country.tour_base
    end
    unless params[:region_id].nil?
      @region = Region.find(params[:region_id])
      @tour_bases = @region.tour_base
    end
    unless params[:city_id].nil?
      @city = City.find(params[:city_id])
      @tour_bases = @city.tour_base
    end

    @countries = Country.all
    @regions = @country.nil? ? Region.all : @country.regions
    @cities = @region.nil? ? City.all : @region.cities
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<div class="row">
  <div class="col-md-5">
    <%= form_with model: @city do |form| %>
      <div>
        <%= form.label :name,"Имя",class:"form-label",required:true %>
        <%= form.text_field :name,class:"form-control" + " is-invalid"*@city.errors.full_messages_for(:name).length %>
        <% puts @city.errors.full_messages_for(:name).each do |message| %>
          <div class="invalid-feedback"><%= message %></div>
        <% end %>
      </div>
      <br/>
      <div>
        <label>Регион</label>
        <%= form.collection_select :region_id, Region.all, :id, :name,{},{class: "form-select"} %>
      </div>
      <br/>
      <div>
        <%= form.submit "Сохранить",class:"btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/cities/edit.html.erb
<%= render "form" %>

app/views/cities/index.html.erb
  <% unless @region.nil? %>
    <h3>Города в регионе: <%= @region.name %></h3>
    <br/>
  <% end %>
  <div class="table-wrapper">
  <table class="table table-bordered">
    <thead>
    <tr>
      <th scope="col">Название</th>
      <th scope="col">Регион</th>
      <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.region.name %></td>
        <td class="table__actions">
          <%= link_to edit_city_path(city),class:"btn btn-outline-warning" do %>
            <i class="bi bi-pencil-fill"></i>
          <% end %>
          <%= link_to city_path(city),method: :delete,class:"btn btn-outline-danger",remote: true, data: {confirm: "Вы уверены?"} do %>
            <i class="bi bi-trash-fill"></i>
          <% end %>
          <%= link_to city_tour_bases_path(city),class:"btn btn-outline-primary" do %>
            Турбазы
          <% end %>

        </td>
      </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <td colspan="3"><a class="btn btn-outline-success" href="<%= new_city_path %>"><i class="bi bi-plus"></i></a></td>
    </tr>
    </tfoot>
  </table>
  </div>

app/views/cities/new.html.erb
<%= render "form" %>

app/views/countries/_form.html.erb
<div class="row">
  <div class="col-md-5">
    <%= form_with model: @country do |form| %>
      <div>
        <%= form.label :name,"Имя",class:"form-label",required:true %>
        <%= form.text_field :name,class:"form-control"+" is-invalid"*@country.errors.full_messages_for(:name).length %>
        <% puts @country.errors.full_messages_for(:name).each do |message| %>
          <div class="invalid-feedback"><%= message %></div>
        <% end %>
      </div>
      <br/>
      <div>
        <%= form.submit "Сохранить",class:"btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/countries/edit.html.erb
<%= render "form", country: @country %>

app/views/countries/index.html.erb
<div class="table-wrapper">
  <table class="table table-bordered">
    <thead>
    <tr>
      <th scope="col">Название</th>
      <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    <% @countries.each do |country| %>
    <tr>
      <td><%= country.name %></td>
      <td class="table__actions">
        <%= link_to edit_country_path(country),class:"btn btn-outline-warning" do %>
          <i class="bi bi-pencil-fill"></i>
        <% end %>
        <%= link_to country_path(country),method: :delete,class:"btn btn-outline-danger",data: {confirm: "Вы уверены? #{country.delete_confirm}"}, remote: true do %>
          <i class="bi bi-trash-fill"></i>
        <% end %>
        <%= link_to country_regions_path(country),class:"btn btn-outline-primary" do %>
          Регионы
        <% end %>
        <%= link_to country_tour_bases_path(country),class:"btn btn-outline-primary" do %>
          Турбазы
        <% end %>
      </td>
    </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <td colspan="2"><a class="btn btn-outline-success" href="<%= new_country_path %>"><i class="bi bi-plus"></i></a></td>
    </tr>
    </tfoot>
  </table>
</div>

app/views/countries/new.html.erb
<%= render "form", country: @country %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Турбазы</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="<%= view_tour_bases_path %>">Просмотр</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Редактирование
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="<%= countries_path %>">Страны</a></li>
              <li><a class="dropdown-item" href="<%= regions_path %>">Регионы</a></li>
              <li><a class="dropdown-item" href="<%= cities_path %>">Города</a></li>
              <li><a class="dropdown-item" href="<%= tour_bases_path %>">Турбазы</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
    <div class="container-fluid p-xs-5">
    <%= yield %>
    </div>
  </body>
</html>

app/views/regions/_form.html.erb
<div class="row">
  <div class="col-md-5">
    <%= form_with model: @region do |form| %>
      <div>
        <%= form.label :name,"Имя",class:"form-label",required:true %>
        <%= form.text_field :name,class:"form-control" + " is-invalid"*@region.errors.full_messages_for(:name).length %>
        <% puts @region.errors.full_messages_for(:name).each do |message| %>
          <div class="invalid-feedback"><%= message %></div>
        <% end %>
      </div>
      <br/>
      <div>
        <label>Страна</label>
        <%= form.collection_select :country_id, Country.all, :id, :name,{},{class: "form-select"} %>
      </div>
      <br/>
      <div>
        <%= form.submit "Сохранить",class:"btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/regions/index.html.erb
  <% unless @country.nil? %>
    <h3>Регионы в стране: <%= @country.name %></h3>
    <br/>
  <% end %>
  <div class="table-wrapper">
  <table class="table table-bordered">
    <thead>
    <tr>
      <th scope="col">Название</th>
      <th scope="col">Страна</th>
      <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    <% @regions.each do |region| %>
      <tr>
        <td><%= region.name %></td>
        <td><%= region.country.name %></td>
        <td class="table__actions">
          <%= link_to edit_region_path(region),class:"btn btn-outline-warning" do %>
            <i class="bi bi-pencil-fill"></i>
          <% end %>
          <%= link_to region_path(region),method: :delete,class:"btn btn-outline-danger",remote: true,data: {confirm: "Вы уверены? #{region.delete_confirm}"} do %>
            <i class="bi bi-trash-fill"></i>
          <% end %>
          <%= link_to region_cities_path(region),class:"btn btn-outline-primary" do %>
            Города
          <% end %>
          <%= link_to region_tour_bases_path(region),class:"btn btn-outline-primary" do %>
            Турбазы
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <td colspan="3"><a class="btn btn-outline-success" href="<%= new_region_path %>">
        <i class="bi bi-plus"></i></a>
      </td>
    </tr>
    </tfoot>
  </table>
  </div>

app/views/tour_bases/_form.html.erb
<div class="row">
  <div class="col-md-5">
    <%= form_with model: @tour_base do |form| %>
      <div>
        <%= form.label :name,"Название",class:"form-label",required:true %>
        <%= form.text_field :name,class:"form-control" + " is-invalid"*@tour_base.errors.full_messages_for(:name).length %>
        <% puts @tour_base.errors.full_messages_for(:name).each do |message| %>
          <div class="invalid-feedback"><%= message %></div>
        <% end %>
      </div>
      <br/>
      <div>
        <%= form.label :description,"Описание",class:"form-label",required:true %>
        <%= form.text_area :description,class:"form-control" + " is-invalid"*@tour_base.errors.full_messages_for(:description).length %>
        <% puts @tour_base.errors.full_messages_for(:name).each do |message| %>
          <div class="invalid-feedback"><%= message %></div>
        <% end %>
      </div>
      <br/>
      <div>
        <label>Регион</label>
        <%= form.collection_select :region_id, Region.all, :id, :name,{},{class: "form-select"} %>
      </div>
      <br/>
      <div>
        <label>Город</label>
        <%= form.collection_select :city_id, City.all, :id, :name,{:include_blank => "Вне города"},
                                   {class: "form-select"} %>
      </div>
      <br/>
      <div>
        <%= form.submit "Сохранить",class:"btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/tour_bases/index.html.erb
  <% unless @region.nil? %>
    <h3>Турбазы в регионе: <%= @region.name %></h3>
    <br/>
  <% end %>
  <% unless @city.nil? %>
    <h3>Турбазы в городе: <%= @city.name %></h3>
    <br/>
  <% end %>
  <% unless @country.nil? %>
    <h3>Турбазы в стране: <%= @country.name %></h3>
    <br/>
  <% end %>
  <div class="table-wrapper">
  <table class="table table-bordered">
    <thead>
    <tr>
      <th scope="col">Название</th>
      <th scope="col">Описание</th>
      <th scope="col">Регион</th>
      <th scope="col">Город</th>
      <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    <% @tour_bases.each do |tour_base| %>
      <tr>
        <td><%= tour_base.name %></td>
        <td><%= tour_base.description %></td>
        <td>
          <%= link_to tour_base.region.name, edit_region_path(tour_base.region) %>
        </td>
        <td>
          <%= tour_base.city.nil? ? "Вне города" : link_to(tour_base.city.name, edit_city_path(tour_base.city)) %>
        </td>
        <td>
          <%= link_to edit_tour_basis_path(tour_base), class:"btn btn-outline-warning" do %>
            <i class="bi bi-pencil-fill"></i>
          <% end %>
          <%= link_to tour_basis_path(tour_base), method: :delete, class:"btn btn-outline-danger", remote: true, data: {confirm: "Вы уверены?"} do %>
            <i class="bi bi-trash-fill"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <td colspan="5"><a class="btn btn-outline-success" href="<%= new_tour_basis_path %>">
        <i class="bi bi-plus"></i></a>
      </td>
    </tr>
    </tfoot>
  </table>
  </div>

app/views/view/tour_bases/_filters.html.erb
<h5>Фильтры</h5>
<br/>
<div class="accordion">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Страны
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne">
      <div class="accordion-body">
        <% @countries.each do |country| %>
          <%= link_to country.name, view_country_tour_bases_path(country),class:country==@country ? "link-dark" : "" %><br/>
        <% end %>
        <%= link_to "Все страны", view_tour_bases_path,class:@country.nil? ? "link-dark" : "" %><br/>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button <%= @region.nil? ? "collapsed" : "" %>" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        Регионы
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse <%= @region.nil? ? "" : "show" %>" aria-labelledby="headingTwo">
      <div class="accordion-body">
        <% @regions.each do |region| %>
          <%= link_to region.name, view_country_region_tour_bases_path(region.country,region),class:region==@region ? "link-dark" : "" %><br/>
        <% end %>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button <%= @city.nil? ? "collapsed" : "" %>" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        Города
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse <%= @city.nil? ? "" : "show" %>" aria-labelledby="headingThree">
      <div class="accordion-body">
        <% @cities.each do |city| %>
          <%= link_to city.name, view_country_region_city_tour_bases_path(city.region.country,city.region,city),class:city==@city ? "link-dark" : "" %><br/>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/view/tour_bases/index.html.erb
<div class="row">
  <div class="col-md-3 p-3">
    <div class="shadow bg-body rounded p-3">
      <%= render "filters" %>
    </div>
  </div>
  <div class="col-md-9">
    <% if !@city.nil? %>
      <h3>Турбазы в городе: <%= @city.name %></h3>
      <br/>
    <% elsif !@region.nil? %>
      <h3>Турбазы в регионе: <%= @region.name %></h3>
      <br/>
    <% elsif !@country.nil? %>
      <h3>Турбазы в стране: <%= @country.name %></h3>
      <br/>
    <% end %>
    <div class="row masonry-grid">
      <% if @tour_bases.length == 0 %>
        <h4>Турбаз нет</h4>
      <% else %>
        <% @tour_bases.each do |tour_base| %>
          <div class="col-md-4 p-3">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title"><%= tour_base.name %></h5>
                <p class="card-text"><%= tour_base.description %></p>
                <%= link_to tour_base.region.name, view_country_region_tour_bases_path(tour_base.region.country,tour_base.region),class: "card-link" %>
                <%= tour_base.city.nil? ? "" : link_to(tour_base.city.name,
                                                       view_country_region_city_tour_bases_path(tour_base.city.region.country,tour_base.city.region,tour_base.city),class: "card-link") %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>